version: "3.6"

services:
  # TODO find somewhere to host videos, and fix.
  # ffmpeg:
  #   build: ./Dockerfile.ffmpeg.arm
  #   image: ffmpeg

  bot:
    build:
      args:
        base_image: arm32v7/node:10.6.0-slim
    environment:
      LIVE: 1
